kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: logos
subjects:
  - kind: ServiceAccount
    name: cicd
    namespace: logos
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io
