apiVersion: apps/v1
kind: Deployment
metadata:
  name: zakolko-app
  namespace: logos
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zakolko-backend
  template:
    metadata:
      labels:
        name: zakolko-backend
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          image: quarkus7/zakolko:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zakolko-service
  namespace: logos
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: zakolko-backend
