# Default values for xavier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

name: zakolko
namespace: logos

image:
  name: backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  portName: http
