apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.name }}-ingress"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - secretName: zakolo-tls
      hosts:
        - hodnotabytu.sk
  rules:
  - host: hodnotabytu.sk
    http:
      paths:
        - path: /
          backend:
            serviceName: zakolko-service
            servicePort: {{ .Values.service.port }}
  - host: www.hodnotabytu.sk
    http:
      paths:
        - path: /
          backend:
            serviceName: zakolko-service
            servicePort: {{ .Values.service.port }}
