apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    name: zakolko-backend
